apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  labels:
    app: log-processing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-ha
  labels:
    app: log-processing
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-ha
  labels:
    app: log-processing
subjects:
  - kind: ServiceAccount
    name: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-ha