apiVersion: v1
kind: Service
metadata:
  name: file-ingestion
  labels:
    app: file-ingestion
spec:
  type: ClusterIP
  selector:
    app: file-ingestion
  ports:
    - name: http
      port: 8080
      targetPort: 8080