apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra
  labels:
    app: cassandra
data:
  CASSANDRA_CLUSTER_NAME: "logging-cluster"
  CASSANDRA_DC: "datacenter1"
  CASSANDRA_RACK: "rack1"
  CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
  CASSANDRA_RPC_ADDRESS: "0.0.0.0"
  MAX_HEAP_SIZE: "1G"
  HEAP_NEWSIZE: "256M"