#################################
# JSON Parser
#################################

[PARSER]
    Name        json_parser
    Format      json


#################################
# CSV Parser
#################################

[PARSER]
    Name        csv_parser
    Format      regex
    Regex       ^(?<logId>[^,]+),(?<host>[^,]+),(?<timestamp>[^,]+),(?<service>[^,]+),(?<instanceId>[^,]+),(?<namespace>[^,]+),(?<podName>[^,]+),(?<traceId>[^,]+),(?<level>[^,]+),(?<message>.*)$


#################################
# Log Parser
#################################

[PARSER]
    Name        log_parser
    Format      regex
    Regex       ^\[(?<timestamp>[^\]]+)\]\s+\[(?<level>[^\]]+)\]\s+\[(?<service>[^\]]+)\]\s+\[(?<host>[^\]]+)\]\s+logId=(?<logId>\S+)\s+instanceId=(?<instanceId>\S+)\s+namespace=(?<namespace>\S+)\s+podName=(?<podName>\S+)\s+traceId=(?<traceId>\S+)\s+-\s+(?<message>.*?)\s+\|\s+(?<attributes>.*)$
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%SZ