# Never used these
kafka.bootstrap.servers=localhost:9092
aws.region=ap-south-1

# ElasticSearch
elasticsearch.host=localhost
elasticsearch.port=9200

# Flink
parallelism=4

# Cassandra
cassandra.contact-points=cassandra-1,cassandra-2,cassandra-3
cassandra.port=9042
cassandra.local-datacenter=datacenter1
cassandra.keyspace=logging

cassandra.max-batch-log-events=1000
cassandra.max-batch-size-bytes=4194304
cassandra.flush-interval-ms=1000
cassandra.max-concurrent-requests=128
cassandra.max-retries=5

# S3
s3.bucket=logging
s3.endpoint=http://minio:9000
s3.access-key=minioadmin
s3.secret-key=minioadmin

# Kafka
input.topic.name="logs.raw"
processed.topic.name="logs.parsed"
failed.topic.name="logs.failed"