# Kafka
kafka.bootstrap.servers=kafka:9092
kafka.group.id=log-processing-group
kafka.raw.topic=logs.raw
kafka.processed.topic=logs.parsed
kafka.failed.topic=logs.failed

# ElasticSearch
elasticsearch.host=elasticsearch
elasticsearch.port=9200

# Cassandra
cassandra.contact-points=cassandra
cassandra.port=9042
cassandra.local-datacenter=datacenter1
cassandra.keyspace=logging

cassandra.max-batch-log-events=1000
cassandra.max-batch-size-bytes=4194304
cassandra.flush-interval-ms=1000
cassandra.max-concurrent-requests=128
cassandra.max-retries=5

# S3
s3.bucket=logging
s3.endpoint=http://minio:9000
s3.access-key=admin
s3.secret-key=minioadmin