kafka.bootstrap.servers=localhost:9092
kafka.topic=logs

aws.region=ap-south-1
s3.bucket=logs-bucket

elasticsearch.host=localhost
elasticsearch.port=9200

parallelism=4
input.topic.name="logs.raw"
processed.topic.name="logs.parsed"